### ISSUE TITLE
All traffic seems to go through Oracle server

### ISSUE THREAD

**Issue by Ginpachi98** [mochman/Bypass_CGNAT#10]
I've been using torrent a bit, and noticed that traffic on vps is huge when I checked with vnstat(50GB, which is how much I downloaded roughly). Then I looked up my IP address as seen from my home server and it shows VPS's public IP. Is it supposed to route traffic like this for all things, or I made mistake while setting it up? I just ran scripts on both ends and it works flawlessly.

Would you suggest I make VM on said server and run the protocol there? Or is there better solution so not all traffic goes through VPS as it does now

**Comment by mochman** [comment]
Would you mind putting your PostUp/PostDown from your VPS's wp0.conf file up here?  There were 2 different versions of that script.  The old one pushed all data through to your local server while the new one just forwards traffic on the specific ports you specify.

To make sure I understand about your setup, are you saying you are running a bittorrent client on your local server?  And you don't want that traffic to flow through your VPS, but to go through your normal home router instead?

**Comment by Ginpachi98** [comment]
Yeah, thank you for understanding regardless of my poor explanation.

I'm running qbit client, sonarr, homeassistant, NPM and some other docker containers on that server. I ran given script from VPS directly via SSH as root on that debian installation(Openmediavault) and it worked. I just want the VPN to work one way though, to passthrough traffic that is directed to VPS@oracle to NPM, and all other traffic from home server should just use router. 

Also:
>host myip.opendns.com resolver1.opendns.com
> myip.opendns.com has address <oracle_server_ip>


VPS /etc/wireguard/wg0.conf

> PrivateKey = <the_key>
> ListenPort = 55108
> Address = 10.1.0.1/24
> 
> PostUp = iptables -t nat -A PREROUTING -p tcp -i ens3 --match multiport --dports                          443,80 -j DNAT --to-destination 10.1.0.2
> PostUp = iptables -t nat -A POSTROUTING -o ens3 -j SNAT --to-source 10.0.0.203
> 
> PostDown = iptables -t nat -D PREROUTING -p tcp -i ens3 --match multiport --dpor                         ts 443,80 -j DNAT --to-destination 10.1.0.2
> PostDown = iptables -t nat -D POSTROUTING -o ens3 -j SNAT --to-source 10.0.0.203
> 
> [Peer]
> PublicKey = <the_key>
> AllowedIPs = 10.1.0.2/32


Local server /etc/wireguard/wg0.conf

> [Interface]
> PrivateKey = <the_key>
> Address = 10.1.0.2/24
> 
> [Peer]
> PublicKey = <the_key>
> AllowedIPs = 0.0.0.0/0
> Endpoint = <oracle_ip_address>:55108
> PersistentKeepalive = 25


Thank you for your time.

**Comment by mochman** [comment]
That is strange.  Can you verify that your torrent IP address is the VPS, instead of your ISP IP.  Using the torrent section of https://ipleak.net/?  If it is your VPS address, can you run (on your local server):
`sudo iptables -S`
`sudo iptables -t nat -S`
`ip route list`
and post those responses.

**Comment by Ginpachi98** [comment]
Yeah, I added magnet link to qbit on that server which runs wireguard and it gives oracle server ip address, 138.x.x.x. While on my pc it's from my ISP -> 46.x.x.x 

sudo iptables -S https://pastebin.com/1xYAZDqP
sudo iptables -t nat -S https://pastebin.com/PNLvZUW0
ip route list https://pastebin.com/UBqJn01b

**Comment by mochman** [comment]
I am looking up split tunneling with wireguard to try and fix this issue.
Can you try to change your local server's wireguard config.
Change `AllowedIPs = 0.0.0.0/0` to `AllowedIPs = 10.1.0.0/24` and restarting the local server's wireguard service.

**Comment by Ginpachi98** [comment]
I changed it, and I can't seem to access NPM anymore, but my IP address is ISP's when I check it with ipleak on torrent client. I did reload services in order for conf to take affect. When I put it back to 0.0.0.0/0, it works again

**Comment by mochman** [comment]
Hmm, can you try putting in:
`AllowedIPs = 10.1.0.0/24, 172.X.X.X/32 `
Where the X's is the docker IPs of NPM?

**Comment by Ginpachi98** [comment]
I found that the NPM address is 172.23.0.2/32, from https://pastebin.com/PNLvZUW0 (443,80,81 ports). When I add it like that, can't connect locally to it with (from another pc) 192.168.1.8:81. NPM's subdomains don't work either. When I add 172.32.0.1/32, I'm able to connect to it locally, but proxies don't work nontheless.

**Comment by mochman** [comment]
I'm not really sure how to get the split tunnel to work with your setup.  Maybe try [this website](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/) to see if you can get your setup to work (allowing everything except your local 192.168.1.0/24).  You may want to look at the [bottom of the page](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/#a-better-alternative) first to see their better alternative.

**Comment by Ginpachi98** [comment]
I've tried both ways with the config but it didn't work. I realized I had to activate iptables legacy on Openmediavault for docker. at one point. Does that makes any difference?

**Comment by Ginpachi98** [comment]
I also figured it'd be possible to use VM, but when I try to forward and enter the address 192.168.1.8 with direct attachment of VM it says destination unreachable, works on other IPs on LAN that are not the host's IP. 

But yes, does it use VPN for all access to internet( meaning does >host myip.opendns.com resolver1.opendns.com give VPS_IP) on your local server too, the one that has NPM in topography image, or is it issue related to my configuration? 

Forwarding to other PCs for game servers works like a charm though, the only problem here is the fact I use that server which has connection to VPS for many other things, and I wouldn't like Oracle to terminate my account because of non ethical torrenting.

**Comment by mochman** [comment]
I have never used OMV, so I'm not sure how it's networking is set up.  I'm not sure how to get this VPN to work with your current setup.  I just put all my external apps on a dedicated VM and run wireguard on that VM.  That way I don't have to mess with split tunneling.

**Comment by Ginpachi98** [comment]
Yeah, VM way for wireguard is the way to go; will figure it out with debian buster or something. Thank you very much for your time, it helped me sort it out in general sense 👍

**Comment by Ginpachi98** [comment]
Yeah, installed debian buster VM and being able to choose IP address on Local was life saver, everything works good, and my IP on host is ISP's. Thanks

**Comment by Ginpachi98** [comment]
I also managed to copy wg0.conf made with a script on that VM to a wireguard-docker and use it as is. I just added bridge to the container for internal addressing with host, and a macvlan for port forwarding to other devices with LAN IP's. Works like a charm, takes only 1MB of RAM, and is better solution to my specific problem.

**Comment by alucryd** [comment]
Also running into this, I haven't found a workaround yet. It seemed putting `Table = off` in the server configuration on my local server would do the trick according to the manpage, but all traffic that comes from outside the VPS doesn't come through, even with `0.0.0.0/0` as allowed IPs, only traffic comig directly from the VPS machine itself is let through. Also tried deleting the route after the VPN is up, but didn't seem to help either.

**Comment by Ginpachi98** [comment]
If you are able to use docker just copy wg0.conf file you made with the script and use it as .conf in cmulk/wireguard-docker

change ip address to 172.X.0.1; X being the bridge network number

**Comment by alucryd** [comment]
Yeah, will probably do that, I already have some podman pods on that server, thx.

**Comment by alucryd** [comment]
Worked like a charm with podman as well! Went with the linuxserver image since I already had a bunch of their stuff on my server.

**Comment by nlitend1** [comment]
@Ginpachi98 @alucryd is running the client in docker still working? I would really like to get the client and into a docker as well, but I can’t seem to figure out where exactly to put the bridge IP address. Could you kindly explain exactly where it goes or even post an example client wg0.conf? I have roughly 20hrs invested in trying to get a working VPS proxy. Running it directly on the host works but I would really like to limit the traffic to only docker. Any advice would certainly be appreciated.

**Comment by Ginpachi98** [comment]
follow this guide to create wg0.conf

PrivateKey = #######################
Address = 10.1.0.2/24

PostUp = iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 172.20.0.1:443; iptables -t nat -A POSTROUTING -p tcp --dport 443 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 443 -j DNAT --to-destination 172.20.0.1:443; iptables -t nat -D POSTROUTING -p tcp --dport 443 -j MASQUERADE

PostUp = iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 172.20.0.1:80; iptables -t nat -A POSTROUTING -p tcp --dport 80 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 80 -j DNAT --to-destination 172.20.0.1:80; iptables -t nat -D POSTROUTING -p tcp --dport 80 -j MASQUERADE


[Peer]
PublicKey =########################
AllowedIPs = 0.0.0.0/0
Endpoint = 138.3.244.7:55108
PersistentKeepalive = 25


this is how mine looks like
172.20.0.1 is docker bridge network
i use it to pass the port to the nginx proxy manager it works really nice

use this docker: https://hub.docker.com/r/cmulk/wireguard-docker
with these settings in a stack:
docker run -d \
--privileged \
--restart=always \
--name wireguard-client \
--cap-add NET_ADMIN \
--cap-add SYS_MODULE \
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
-v <client config dir>wg0.conf:/etc/wireguard/wg0.conf \
cmulk/wireguard-docker:alpine

It works well outside of bridge network you are without vpn while inside you use vpn and passthrough it to host for the proxy manager; you could even use it bind it to proxymanager's ip but this is less of a hassle

**Comment by Ginpachi98** [comment]
follow CGNAT guide to create wg0.conf for server and yourself, in my case its like this

PrivateKey = #######################
Address = 10.1.0.2/24

PostUp = iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 172.20.0.1:443; iptables -t nat -A POSTROUTING -p tcp --dport 443 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 443 -j DNAT --to-destination 172.20.0.1:443; iptables -t nat -D POSTROUTING -p tcp --dport 443 -j MASQUERADE

PostUp = iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 172.20.0.1:80; iptables -t nat -A POSTROUTING -p tcp --dport 80 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -p tcp --dport 80 -j DNAT --to-destination 172.20.0.1:80; iptables -t nat -D POSTROUTING -p tcp --dport 80 -j MASQUERADE


[Peer]
PublicKey =########################
AllowedIPs = 0.0.0.0/0
Endpoint = #######:55108
PersistentKeepalive = 25


this is how mine looks like
172.20.0.1 is docker bridge network gateway(host)
i use it to pass the port to the nginx proxy manager it works really nice

use this docker: https://hub.docker.com/r/cmulk/wireguard-docker
with these settings in a stack:
docker run -d \
--privileged \
--restart=always \
--name wireguard-client \
--cap-add NET_ADMIN \
--cap-add SYS_MODULE \
--sysctl net.ipv6.conf.all.disable_ipv6=0 \
-v client config dir/wg0.conf:/etc/wireguard/wg0.conf \
cmulk/wireguard-docker:alpine

It works well outside of bridge network you are without vpn while inside you use vpn and passthrough it to host for the proxy manager; you could even use it bind it to proxymanager's ip but this is less of a hassle
