### ISSUE TITLE
Add ports after initial setup

### ISSUE THREAD

**Issue by randomodbuild** [mochman/Bypass_CGNAT#2]
Could one add additional ports to allow after the initial setup? For example, if a person wanted to setup another service that required more ports to be exposed, those could be added without having to start fresh.

**Comment by randomodbuild** [comment]
Feeling silly right now. I figured out what was going on and this issue isn't necessary. Sorry to bother

**Comment by mochman** [comment]
No worries.  Your question did get me thinking about allowing the script to just update the ports, instead of having to reinstall everything all over again.  Thanks.
