### ISSUE TITLE
Problem - iptables need to be installed in ubuntu

### ISSUE THREAD

**Issue by saifalbadi** [mochman/Bypass_CGNAT#25]
### Terms

- [X] This request is not a duplicate of an existing issue.
- [X] I have provided as much information as I can to help resolve this issue.

### Description

iptables service not installed or whatever

### steps-to-reproduce

sudo apt install iptables -y

### Actual Behavior

not connecting

### Script Version

latest

**Comment by mochman** [comment]
Closed - No real information provided.
