### ISSUE TITLE
Problem - Unable to complete the setup using script

### ISSUE THREAD

**Issue by shreyaspg** [mochman/Bypass_CGNAT#26]
### Terms

- [X] This request is not a duplicate of an existing issue.
- [X] I have provided as much information as I can to help resolve this issue.

#### Describe the problem.

I have a local server (A) and a vps (B). I followed the steps in the wiki, and after running the script 'Oracle Installer.sh' . I get a error from the wg-quick@wg0.service, 
any help would be great, Thanks..

#### A clear and concise description 

```
From VPS

That script will output a public key for you to input here.
Public Key from Client: wROe+0csk5iEap5mFXOi9pgj8M8MQVzvmdYJPCgKjD8=
Wireguard Config file created at /etc/wireguard/wg0.conf

Starting Wireguard...Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xeu wg-quick@wg0.service" for details.
[Done]


journalctl output 
$journalctl -xeu wg-quick@wg0.service
Jul 05 04:40:07 node wg-quick[2938]: Warning: `/etc/wireguard/wg0.conf' is world accessible
Jul 05 04:40:07 node wg-quick[2938]: [#] ip link add wg0 type wireguard
Jul 05 04:40:07 node wg-quick[2938]: [#] wg setconf wg0 /dev/fd/63
Jul 05 04:40:07 node wg-quick[2950]: Line unrecognized: `zt44xjouew--matchmultiport--dports443,80,32400-jDNAT--to-destination10.1.0.2'
Jul 05 04:40:07 node wg-quick[2950]: Configuration parsing error
Jul 05 04:40:07 node wg-quick[2938]: [#] ip link delete dev wg0
Jul 05 04:40:08 node systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE

From Local server
Jul 05 10:09:57 raspberrypi wg-quick[29360]: [#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
Jul 05 10:09:57 raspberrypi wg-quick[29360]: [#] iptables-restore -n
Jul 05 10:09:57 raspberrypi wg-quick[29360]: iptables-restore v1.8.2 (nf_tables): Couldn't load match `comment':No such file or directory
Jul 05 10:09:57 raspberrypi wg-quick[29360]: Error occurred at line: 2
Jul 05 10:09:57 raspberrypi wg-quick[29360]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Jul 05 10:09:57 raspberrypi wg-quick[29360]: [#] ip -4 rule delete table 51820
Jul 05 10:09:57 raspberrypi wg-quick[29360]: [#] ip -4 rule delete table main suppress_prefixlength 0
Jul 05 10:09:57 raspberrypi wg-quick[29360]: [#] ip link delete dev wg0
Jul 05 10:09:58 raspberrypi systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

```

### steps-to-reproduce

VPS:
./Oracle_Installer.sh , all default values nothing changed, ports 443/tcp,80/tcp,32400/tcp,32400/udp

Local Server:
./Oracle_Installer.sh Local <-key-> <-public ip vm-> 10.1.0.1 10.1.0.2 55108 443/tcp,80/tcp,32400/tcp,32400/udp

### Actual Behavior

```
Starting Wireguard...Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xeu wg-quick@wg0.service" for details.
[Done]
```

### Script Version

Version 0.2.0 

### VPS wireguard config (/etc/wireguard/wg0.conf)

```shell
[Interface]
PrivateKey = <-priv-key->
ListenPort = 55108
Address = 10.1.0.1/24

PostUp = iptables -t nat -A PREROUTING -p tcp -i scope
zt44xjouew --match multiport --dports 443,80,32400 -j DNAT --to-destination 10.1.0.2
PostUp = iptables -t nat -A POSTROUTING -o scope
zt44xjouew -j SNAT --to-source 10.0.0.236
10.242.121.108
PostUp = iptables -t nat -A PREROUTING -p udp -i scope
zt44xjouew --match multiport --dports 32400 -j DNAT --to-destination 10.1.0.2;

PostDown = iptables -t nat -D PREROUTING -p tcp -i scope
zt44xjouew --match multiport --dports 443,80,32400 -j DNAT --to-destination 10.1.0.2
PostDown = iptables -t nat -D POSTROUTING -o scope
zt44xjouew -j SNAT --to-source 10.0.0.236
10.242.121.108
PostDown = iptables -t nat -D PREROUTING -p udp -i scope
zt44xjouew --match multiport --dports 32400 -j DNAT --to-destination 10.1.0.2;

[Peer]
PublicKey = <-pub-key->
AllowedIPs = 10.1.0.2/32
```

### Local Server wireguard config (/etc/wireguard/wg0.conf)

```shell
[Interface]
PrivateKey = <-priv-key->
Address = 10.1.0.2/24

## iptable rules similar to vps

[Peer]
PublicKey = <-key->
AllowedIPs = 0.0.0.0/0
Endpoint = <-public_ip->:55108
PersistentKeepalive = 25
```

**Comment by mochman** [comment]
It looks like the script didn't parse your VPS's network interface correctly.  In the VPS's `wg0.conf` file
```
PostUp = iptables -t nat -A PREROUTING -p tcp -i scope
zt44xjouew --match multiport --dports 443,80,32400 -j DNAT --to-destination 10.1.0.2
...
```
the section after `-i` shouldn't say `scope zt44xjouew`, it should be your network interface.  On my Oracle VPS, the interface is called `ens3`.  On my Digital Ocean one, it's called `eth0`.  
You will need to change all of the `PostUp` & `PostDown` sections of your wg0.conf to replace `scope zt44xjouew` with your network interface name.

So I can modify my script, what VPS are you using?  Would you mind providing the output of `ifconfig -a | sed 's/[ \t].*//;/^$/d'` as well?  Thank you.

**Comment by shreyaspg** [comment]
I'm using Oracle VPS (Arm Ampere).  Let me try replacing with the right interface in the Post Sections
Here's the output of ifconfig :
```
$ ifconfig -a | sed 's/[ \t].*//;/^$/d'
br-0d4d2bfb304c:
docker0:
enp0s3:
lo:
vethdbf212b:
zt44xjouew:
ztukuuct2c:
```
Thank you,

**Comment by nimdy2017** [comment]
> It looks like the script didn't parse your VPS's network interface correctly. In the VPS's `wg0.conf` file
> 
> ```
> PostUp = iptables -t nat -A PREROUTING -p tcp -i scope
> zt44xjouew --match multiport --dports 443,80,32400 -j DNAT --to-destination 10.1.0.2
> ...
> ```
> 
> the section after `-i` shouldn't say `scope zt44xjouew`, it should be your network interface. On my Oracle VPS, the interface is called `ens3`. On my Digital Ocean one, it's called `eth0`. You will need to change all of the `PostUp` & `PostDown` sections of your wg0.conf to replace `scope zt44xjouew` with your network interface name.
> 
> So I can modify my script, what VPS are you using? Would you mind providing the output of `ifconfig -a | sed 's/[ \t].*//;/^$/d'` as well? Thank you.

The network adapter name is enp0s3 on my Oracle VPS. This might be because the configuration might be different for the ARM Ampere servers to the x86

**Comment by mochman** [comment]
Thanks.  I haven't tried using the ARM VM on Oracle.  I will modify the script to account for that.  Thanks for the help.  @shreyaspg Does using `enp0s3` work for you?

**Comment by mochman** [comment]
I have a modified script [here](https://raw.githubusercontent.com/mochman/Bypass_CGNAT/Port/Interface-Selection/Oracle%20Cloud/Oracle_Installer.sh) that you can try.  I just spun up an ARM server and I only have `lo` and `enp0s3` for network interfaces.  So I'm not sure how this will work with your other 5 network interfaces.

**Comment by shreyaspg** [comment]
I used the above script, and It no longer throws the error, Thanks a lot ..!!
```

Wireguard Config file created at /etc/wireguard/wg0.conf

Starting Wireguard...[Done]
Waiting for connection...
```
