### ISSUE TITLE
Problem - Oracle script uses wrong interface

### ISSUE THREAD

**Issue by Herjar** [mochman/Bypass_CGNAT#31]
### Terms

- [X] This request is not a duplicate of an existing issue.
- [X] I have provided as much information as I can to help resolve this issue.

#### Describe the problem.

Using the automatic setup did not work correctly for me. The interface set in the server config was 'scope', which does not exist. I changed the interface to 'ens3' and it worked fine.

### steps-to-reproduce

1. Run automatic setup
2. Check /etc/wireguard/wg0.conf
3. Wrong interface is used

### Actual Behavior

Wrong interface is used

### Script Version

0.2.0

**Comment by mochman** [comment]
These fixes should work.  Thanks for letting me know about the problem.

**Comment by HotshotGT** [comment]
Just chiming in to say that I ran into this exact behavior today while setting up a new instance. Changing "scope" to "ens3" worked perfectly for me as well.
