### ISSUE TITLE
Oracle VPS not connecting to CF

### ISSUE THREAD

**Issue by just5ky** [mochman/Bypass_CGNAT#8]
So after the new update, I am not able to transfer data to CF.
The script works perfectly before the latest update.

I tried running the old script, it gives the following error
```
root@justsky-10gbps:/home/ubuntu# ./Oracle_Installer.sh
./Oracle_Installer.sh: line 7: syntax error near unexpected token `newline'
./Oracle_Installer.sh: line 7: `<!DOCTYPE html>'
root@justsky-10gbps:/home/ubuntu#
```

Can you please tell me how to uninstall and run from the old v1.0 script?

I have followed all the steps perfectly.
Open the ports mentioned
my local server can reach VPS with no issue
![image](https://user-images.githubusercontent.com/71321862/140181294-25607307-389e-4bab-9e9f-293ef2132c73.png)

**Comment by mochman** [comment]
You can always get the script from an old commit like:
`wget https://raw.githubusercontent.com/mochman/Bypass_CGNAT/14714a8896e7bc3521a04796bf72f910e584cd4b/Oracle%20Cloud/Oracle_Installer.sh`
but that doesn't help me with knowing why the new script doesn't work.  

What errors are you seeing on the new script?

Are you adding all the ports you want pushed through the VPN?

**Comment by just5ky** [comment]
The script was working perfectly before
I forwarded 443/tcp,80/tcp, wireguard_port,22
all my services are going through NginxProxy Manager, so i don't need to forward anything else.

I will try installing from the old commit.

There are no error while running the new script, that's why it took a while to figure out which part of the network was causing the issue.
Should i run the python HTTP server script on the VPS to check again.

**Comment by just5ky** [comment]
I just tested by accessing VPS_PUBLIC_IP:80 and it showed me the NginxProxyManager configuration page.
the script might not be the issue here then
![image](https://user-images.githubusercontent.com/71321862/140259636-e3f63e5a-833d-486c-a2c2-dbe3a7a4a1cc.png)


sorry for creating the issue. i will check if there is any issue with Nginx proxing the requests

**Comment by mochman** [comment]
Can you check your iptables on the VPS?  Maybe the old settings didn't get cleared out before you used the new script?

`sudo iptables -t nat -S`

Unless you've done other stuff to your VPS, you should see 3 rules (after the PREROUTING,INPUT,OUTPUT,POSTROUTING accepts).

There should be 2 PREROUTINGs with your TCP and UDP ports and one POSTROUTING with a SNAT to your public_ip.  Do those look right?

As a side note, you don't need to put in port 22 or your wireguard port into the install script.  The script adds those ports by default.

**Comment by just5ky** [comment]
![image](https://user-images.githubusercontent.com/71321862/140620364-15e0ab44-1b4d-452e-8119-7b70a0016275.png)

It only has 1 PREROUTING and 1 POSTROUTING after the 3 rules.
Going to try with the old script.

**Comment by just5ky** [comment]
Ran the old script.
and now there are 2 PREROUTING after the 3rules
![image](https://user-images.githubusercontent.com/71321862/140620779-3f92323b-f962-4deb-9782-7a497ea048cd.png)

still can't access services from the CF domains, but can access from VPS IP:PORT

**Comment by mochman** [comment]
Sorry, I was looking at my server when I said you should have 2 PREROUTING lines in the new script.  You would have 2 lines if you were forwarding both TCP and UDP.  Since you are forwarding TCP ports only, you would just have the 1 PREROUTING line.

Can you check to see if ufw is running on your VPS and your local server?  `sudo ufw status` 
I'm trying to think of reasons why port 443 isn't working for you.

**Comment by just5ky** [comment]
~ufw shows inactive on both VPS and also Local sever~

created a new configuration and now VPS shows the following
![image](https://user-images.githubusercontent.com/71321862/140655662-d89ca2c8-a5b2-4ead-8fb4-d75d448523f2.png)
Local server shows `Inactive`
![image](https://user-images.githubusercontent.com/71321862/140655680-6ef6d4e6-ec1b-49c7-9ad2-4ceb08206919.png)

**Comment by mochman** [comment]
So those all look fine.
Here is how I would troubleshoot this issue.
1.  Make sure that cloudflare is still pointing to the correct VPS IP.
2.  Stop Nginx Proxy manager then run:

```
cd ~/
mkdir temp_html
cd temp_html
echo "Working" > index.html
sudo python3 -m http.server 443
```
3.  Try going to http://YOUR_VPS_IP:443/
4. If you see a website that says "Working", then you know that the VPN is correctly forwarding port 443.  That means that the VPN is working correctly and your problem exists on your local server somewhere.
5. If the website works, then there may be an issue with the VPN forwarding the ports correctly.
6. You can check your Local Server's iptables to make sure that the ports aren't being dropped for some reason.
```
sudo iptables -S
sudo iptables -t nat -S
```

Don't forget to kill the python web server then start up NPM again when you're done.

**Comment by just5ky** [comment]
The python web server test, and it works.

IDK what I am looking at when it comes to checking if any ports are being dropped.
So here's the result.
![image](https://user-images.githubusercontent.com/71321862/140774200-f32c33f4-29f5-44c8-9bf2-0df5e813b11d.png)
![image](https://user-images.githubusercontent.com/71321862/140774366-abcb538e-a2b0-4f56-a2e4-3e1130bbf303.png)

**Comment by mochman** [comment]
Did you restart NPM before running those iptables commands?  Because there should be a few DOCKER lines in there that route port 443.  Could you restart your local server and run those iptables commands again?

**Comment by just5ky** [comment]
restarted local server, seeing same amount of docker lines

**Comment by mochman** [comment]
Then it looks like there is something wrong with your NPM container, since it's not routing port 443 to the container.

**Comment by just5ky** [comment]
I was using the same NPM image before, not sure how it can cause an issue now

**Comment by mochman** [comment]
Did you assume it should work or did you check it?

**Comment by mochman** [comment]
Closing issue since @Just5KY has shown that the wireguard tunnel works as it should.  Problem with user's setup is on their local server.
