### ISSUE TITLE
[Support] Cant access internal service

### ISSUE THREAD

**Issue by TheDarthFather** [mochman/Bypass_CGNAT#9]
Hello,
Thank you for the guide - very helpful.
I tried to do the same, but I have a challange: My tunnel works, but I cant access my services on 192.168.0.7.
My home server is in a docker, but is on the host network, so it should not be an issue ..
Did I miss something in the configs ?
https://pastebin.com/LW9BPf5N

PS: Amazingly if I delete the fw port 80 ... I land on the home server web ... so without any iptables rule .. or is a backup of 443 !?

**Comment by mochman** [comment]
Can you describe your setup a little more for me?  Is it:
VPS -> wireguard in a docker container @ 192.168.0.8 -> forwarding ports 80 & 25565 to another computer @ 192.168.0.7 ?

**Comment by TheDarthFather** [comment]
Hi,
I just 'fixed' it. It seems I played so much with the rules, and copy-paste that I messed up PostUp & PostDown.
As a result I draw wrong conclusions on what was actualy working and not.
I just restored my both machines from the basic config and added on top - works like a charm!
Thank you again for the great how-to!!!

**Comment by haudamekki** [comment]
Hi,
I have the same problem but i cant figure it out. The tunnel works but i cant connect to internal IP's.
My Setup is AWS Lightsale -> Wireguard on a Proxmox Container(192.168.6.25) (Ihave also tried Wireguard on a Raspberry) -> Npm on another Server(192.168.6.7). And Wireguard to connect with my phone to my network(192.168.6.1)

https://pastebin.com/tSCeL28S

Any Ideas?
